

import { AdvancedContractConfig } from '../../src/types.js';

export const generateContractSource = (config: AdvancedContractConfig): string => {
  if (config.type === 'ERC1155') return generateERC1155Source(config);
  return generateERC721Source(config); 
};



function generateERC721Source(config: AdvancedContractConfig): string {
  const { name, symbol, supply, mint, royalty, advanced } = config;

  const cn = (name || 'MyNFT').replace(/[^a-zA-Z0-9_]/g, '').replace(/^[0-9]+/, '') || 'MyNFT';
  const mintPrice   = mint.publicMint.price || '0';
  const allowPrice  = mint.allowlistMint.price || '0';
  const maxPerTx    = mint.publicMint.maxPerTx || 5;
  const maxWallet   = supply.maxPerWallet || 0;
  const royaltyBps  = royalty.percentage || 500;

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// =================================================================
// ${name} (${symbol}) — ERC-721 NFT
// Generated by Crolana — self-contained, zero dependencies
// =================================================================

// ── String utilities ─────────────────────────────────────────────
library Strings {
    function toString(uint256 value) internal pure returns (string memory) {
        if (value == 0) return "0";
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) { digits++; temp /= 10; }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits--;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }
}

// ── Merkle proof (for allowlist) ─────────────────────────────────
library MerkleProof {
    function verify(bytes32[] memory proof, bytes32 root, bytes32 leaf) internal pure returns (bool) {
        bytes32 h = leaf;
        for (uint256 i = 0; i < proof.length; i++) {
            bytes32 p = proof[i];
            h = h < p ? keccak256(abi.encodePacked(h, p)) : keccak256(abi.encodePacked(p, h));
        }
        return h == root;
    }
}

// ── ERC-721 Receiver interface ────────────────────────────────────
interface IERC721Receiver {
    function onERC721Received(
        address operator, address from, uint256 tokenId, bytes calldata data
    ) external returns (bytes4);
}

contract ${cn} {
    using Strings for uint256;

    // ── Events ───────────────────────────────────────────────────
    event Transfer(address indexed from, address indexed to, uint256 indexed tokenId);
    event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId);
    event ApprovalForAll(address indexed owner, address indexed operator, bool approved);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    event Minted(address indexed to, uint256 qty);
    event Revealed(string newBaseURI);

    // ── ERC-721 storage ──────────────────────────────────────────
    string public name;
    string public symbol;
    mapping(uint256 => address) private _owners;
    mapping(address => uint256) private _balances;
    mapping(uint256 => address) private _tokenApprovals;
    mapping(address => mapping(address => bool)) private _operatorApprovals;

    // ── Ownership ────────────────────────────────────────────────
    address private _owner;

    // ── Reentrancy ───────────────────────────────────────────────
    uint256 private _reentrancyStatus = 1;

    // ── NFT config ───────────────────────────────────────────────
    string public baseURI;
    string public hiddenMetadataUri;
    string private _contractURIValue;

    uint256 public cost = ${mintPrice} ether;
    uint256 public maxSupply = ${supply.maxSupply};
    uint256 public maxMintAmountPerTx = ${maxPerTx};
    ${maxWallet > 0 ? `uint256 public maxMintAmountPerWallet = ${maxWallet};` : ''}
    bool public paused = ${mint.isPaused ? 'true' : 'false'};
    bool public revealed = ${advanced.isRevealed ? 'true' : 'false'};
    ${advanced.isSoulbound ? 'bool public soulbound = true;' : ''}
    ${mint.allowlistMint.enabled ? 'bytes32 public merkleRoot;' : ''}
    uint256 private _tokenIdCounter = 1;
    uint256 private _totalMinted;
    mapping(address => uint256) public mintedByWallet;

    // ── ERC-2981 Royalties ───────────────────────────────────────
    address public royaltyReceiver;
    uint96 public royaltyBps;

    // ── Constructor ──────────────────────────────────────────────
    constructor(string memory _initBaseURI, string memory _initHiddenURI) {
        name = "${name}";
        symbol = "${symbol}";
        _owner = msg.sender;
        royaltyReceiver = msg.sender;
        royaltyBps = ${royaltyBps};
        baseURI = _initBaseURI;
        hiddenMetadataUri = _initHiddenURI;
        emit OwnershipTransferred(address(0), msg.sender);
    }

    // ── Ownership ────────────────────────────────────────────────
    modifier onlyOwner() { require(msg.sender == _owner, "Not owner"); _; }
    function owner() public view returns (address) { return _owner; }
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Zero addr");
        emit OwnershipTransferred(_owner, newOwner);
        _owner = newOwner;
    }
    function renounceOwnership() external onlyOwner {
        emit OwnershipTransferred(_owner, address(0));
        _owner = address(0);
    }

    // ── Reentrancy guard ─────────────────────────────────────────
    modifier nonReentrant() {
        require(_reentrancyStatus != 2, "Reentrant call");
        _reentrancyStatus = 2;
        _;
        _reentrancyStatus = 1;
    }

    // ── ERC-165 ──────────────────────────────────────────────────
    function supportsInterface(bytes4 interfaceId) public pure returns (bool) {
        return interfaceId == 0x80ac58cd  // IERC721
            || interfaceId == 0x5b5e139f  // IERC721Metadata
            || interfaceId == 0x2a55205a  // IERC2981
            || interfaceId == 0x01ffc9a7; // IERC165
    }

    // ── ERC-2981 ─────────────────────────────────────────────────
    function royaltyInfo(uint256, uint256 salePrice) external view returns (address, uint256) {
        return (royaltyReceiver, (salePrice * royaltyBps) / 10000);
    }

    // ── ERC-721 core ─────────────────────────────────────────────
    function totalSupply() public view returns (uint256) { return _totalMinted; }
    function balanceOf(address _addr) public view returns (uint256) {
        require(_addr != address(0), "Zero addr"); return _balances[_addr];
    }
    function ownerOf(uint256 tokenId) public view returns (address) {
        address own = _owners[tokenId]; require(own != address(0), "Nonexistent"); return own;
    }
    function tokenURI(uint256 tokenId) public view returns (string memory) {
        require(_owners[tokenId] != address(0), "Nonexistent");
        if (!revealed) return hiddenMetadataUri;
        return bytes(baseURI).length > 0
            ? string(abi.encodePacked(baseURI, tokenId.toString(), ".json")) : "";
    }
    function contractURI() external view returns (string memory) { return _contractURIValue; }

    function approve(address to, uint256 tokenId) public {
        address own = ownerOf(tokenId);
        require(msg.sender == own || _operatorApprovals[own][msg.sender], "Not authorized");
        _tokenApprovals[tokenId] = to;
        emit Approval(own, to, tokenId);
    }
    function getApproved(uint256 tokenId) public view returns (address) {
        require(_owners[tokenId] != address(0), "Nonexistent"); return _tokenApprovals[tokenId];
    }
    function setApprovalForAll(address operator, bool approved) public {
        require(operator != msg.sender, "Approve self");
        _operatorApprovals[msg.sender][operator] = approved;
        emit ApprovalForAll(msg.sender, operator, approved);
    }
    function isApprovedForAll(address own, address operator) public view returns (bool) {
        return _operatorApprovals[own][operator];
    }

    function transferFrom(address from, address to, uint256 tokenId) public {
        require(_isApproved(msg.sender, tokenId), "Not authorized");
        ${advanced.isSoulbound ? 'require(from == address(0), "Soulbound");' : ''}
        _transfer(from, to, tokenId);
    }
    function safeTransferFrom(address from, address to, uint256 tokenId) public {
        safeTransferFrom(from, to, tokenId, "");
    }
    function safeTransferFrom(address from, address to, uint256 tokenId, bytes memory data) public {
        require(_isApproved(msg.sender, tokenId), "Not authorized");
        ${advanced.isSoulbound ? 'require(from == address(0), "Soulbound");' : ''}
        _transfer(from, to, tokenId);
        _checkReceiver(msg.sender, from, to, tokenId, data);
    }

    function _isApproved(address spender, uint256 tokenId) internal view returns (bool) {
        address own = ownerOf(tokenId);
        return spender == own || _operatorApprovals[own][spender] || _tokenApprovals[tokenId] == spender;
    }
    function _transfer(address from, address to, uint256 tokenId) internal {
        require(ownerOf(tokenId) == from, "Wrong owner");
        require(to != address(0), "Zero addr");
        delete _tokenApprovals[tokenId];
        _balances[from]--;
        _balances[to]++;
        _owners[tokenId] = to;
        emit Transfer(from, to, tokenId);
    }
    function _mint(address to, uint256 tokenId) internal {
        require(to != address(0), "Zero addr");
        require(_owners[tokenId] == address(0), "Already minted");
        _balances[to]++;
        _owners[tokenId] = to;
        _totalMinted++;
        emit Transfer(address(0), to, tokenId);
    }
    function _burn(uint256 tokenId) internal {
        address own = ownerOf(tokenId);
        delete _tokenApprovals[tokenId];
        _balances[own]--;
        delete _owners[tokenId];
        _totalMinted--;
        emit Transfer(own, address(0), tokenId);
    }
    function _checkReceiver(address op, address from, address to, uint256 tokenId, bytes memory data) internal {
        if (to.code.length > 0) {
            try IERC721Receiver(to).onERC721Received(op, from, tokenId, data) returns (bytes4 r) {
                require(r == IERC721Receiver.onERC721Received.selector, "Non-receiver");
            } catch { revert("Non-receiver"); }
        }
    }

    // ── Minting ──────────────────────────────────────────────────
    modifier mintCheck(uint256 qty) {
        require(!paused, "Minting paused");
        require(qty > 0 && qty <= maxMintAmountPerTx, "Invalid quantity");
        require(_totalMinted + qty <= maxSupply, "Max supply exceeded");
        ${maxWallet > 0 ? 'require(mintedByWallet[msg.sender] + qty <= maxMintAmountPerWallet, "Wallet limit exceeded");' : ''}
        _;
    }

    function mint(uint256 qty) external payable nonReentrant mintCheck(qty) {
        require(msg.value >= cost * qty, "Insufficient payment");
        _executeMint(msg.sender, qty);
    }

    ${mint.allowlistMint.enabled ? `
    function allowlistMint(uint256 qty, bytes32[] calldata proof) external payable nonReentrant mintCheck(qty) {
        require(MerkleProof.verify(proof, merkleRoot, keccak256(abi.encodePacked(msg.sender))), "Invalid proof");
        require(msg.value >= ${allowPrice} ether * qty, "Insufficient payment");
        _executeMint(msg.sender, qty);
    }` : ''}

    function ownerMint(address to, uint256 qty) external onlyOwner {
        require(_totalMinted + qty <= maxSupply, "Max supply exceeded");
        for (uint256 i = 0; i < qty; i++) {
            _mint(to, _tokenIdCounter);
            _checkReceiver(msg.sender, address(0), to, _tokenIdCounter, "");
            _tokenIdCounter++;
        }
        emit Minted(to, qty);
    }

    function _executeMint(address to, uint256 qty) internal {
        for (uint256 i = 0; i < qty; i++) {
            _mint(to, _tokenIdCounter);
            _checkReceiver(msg.sender, address(0), to, _tokenIdCounter, "");
            _tokenIdCounter++;
        }
        mintedByWallet[to] += qty;
        emit Minted(to, qty);
    }

    ${advanced.isBurnable ? `
    function burn(uint256 tokenId) external {
        require(_isApproved(msg.sender, tokenId), "Not authorized");
        _burn(tokenId);
    }` : ''}

    // ── Owner admin ──────────────────────────────────────────────
    function reveal(string calldata _newBaseURI) external onlyOwner {
        revealed = true; baseURI = _newBaseURI; emit Revealed(_newBaseURI);
    }
    function setBaseURI(string calldata _uri) external onlyOwner { baseURI = _uri; }
    function setHiddenMetadataUri(string calldata _uri) external onlyOwner { hiddenMetadataUri = _uri; }
    function setCost(uint256 _cost) external onlyOwner { cost = _cost; }
    function setMaxMintAmountPerTx(uint256 _max) external onlyOwner { maxMintAmountPerTx = _max; }
    function setPaused(bool _state) external onlyOwner { paused = _state; }
    function setRevealed(bool _state) external onlyOwner { revealed = _state; }
    ${mint.allowlistMint.enabled ? 'function setMerkleRoot(bytes32 _root) external onlyOwner { merkleRoot = _root; }' : ''}
    function setRoyalty(address recv, uint96 bps) external onlyOwner {
        require(bps <= 1000, "Max 10%"); royaltyReceiver = recv; royaltyBps = bps;
    }
    function setContractURI(string calldata uri) external onlyOwner { _contractURIValue = uri; }

    function withdraw() external onlyOwner nonReentrant {
        uint256 bal = address(this).balance;
        require(bal > 0, "Nothing to withdraw");
        (bool ok,) = payable(_owner).call{value: bal}("");
        require(ok, "Transfer failed");
    }
}
`;
}



function generateERC1155Source(config: AdvancedContractConfig): string {
  const { name, symbol, supply, mint, royalty, advanced } = config;

  const cn = (name || 'MyNFT').replace(/[^a-zA-Z0-9_]/g, '').replace(/^[0-9]+/, '') || 'MyNFT';
  const mintPrice  = mint.publicMint.price || '0';
  const royaltyBps = royalty.percentage || 500;

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// =================================================================
// ${name} (${symbol}) — ERC-1155 Multi-Token NFT
// Generated by Crolana — self-contained, zero dependencies
// =================================================================

// ── String utilities ─────────────────────────────────────────────
library Strings {
    function toString(uint256 value) internal pure returns (string memory) {
        if (value == 0) return "0";
        uint256 temp = value; uint256 digits;
        while (temp != 0) { digits++; temp /= 10; }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits--;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }
}

// ── ERC-1155 Receiver interface ──────────────────────────────────
interface IERC1155Receiver {
    function onERC1155Received(address, address, uint256, uint256, bytes calldata) external returns (bytes4);
    function onERC1155BatchReceived(address, address, uint256[] calldata, uint256[] calldata, bytes calldata) external returns (bytes4);
}

contract ${cn} {
    using Strings for uint256;

    // ── Events ───────────────────────────────────────────────────
    event TransferSingle(address indexed op, address indexed from, address indexed to, uint256 id, uint256 value);
    event TransferBatch(address indexed op, address indexed from, address indexed to, uint256[] ids, uint256[] values);
    event ApprovalForAll(address indexed account, address indexed operator, bool approved);
    event URI(string value, uint256 indexed id);
    event OwnershipTransferred(address indexed prev, address indexed next_);
    event Minted(address indexed to, uint256 id, uint256 amount);

    // ── Storage ──────────────────────────────────────────────────
    string public name = "${name}";
    string public symbol = "${symbol}";
    mapping(uint256 => mapping(address => uint256)) private _balances;
    mapping(address => mapping(address => bool)) private _operatorApprovals;
    string private _uri;
    string private _contractURIValue;
    address private _owner;
    uint256 private _reentrancyStatus = 1;

    uint256 public maxSupply = ${supply.maxSupply};
    uint256 public cost = ${mintPrice} ether;
    bool public paused = ${mint.isPaused ? 'true' : 'false'};
    uint256 private _totalMinted;
    mapping(address => uint256) public mintedByWallet;
    mapping(uint256 => uint256) public tokenSupply;

    address public royaltyReceiver;
    uint96 public royaltyBps;

    // ── Constructor ──────────────────────────────────────────────
    constructor(string memory baseUri) {
        _uri = baseUri;
        _owner = msg.sender;
        royaltyReceiver = msg.sender;
        royaltyBps = ${royaltyBps};
        emit OwnershipTransferred(address(0), msg.sender);
    }

    // ── Ownership ────────────────────────────────────────────────
    modifier onlyOwner() { require(msg.sender == _owner, "Not owner"); _; }
    function owner() public view returns (address) { return _owner; }
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Zero addr");
        emit OwnershipTransferred(_owner, newOwner); _owner = newOwner;
    }

    // ── Reentrancy guard ─────────────────────────────────────────
    modifier nonReentrant() {
        require(_reentrancyStatus != 2, "Reentrant");
        _reentrancyStatus = 2; _; _reentrancyStatus = 1;
    }

    // ── ERC-165 ──────────────────────────────────────────────────
    function supportsInterface(bytes4 interfaceId) public pure returns (bool) {
        return interfaceId == 0xd9b67a26  // IERC1155
            || interfaceId == 0x0e89341c  // IERC1155MetadataURI
            || interfaceId == 0x2a55205a  // IERC2981
            || interfaceId == 0x01ffc9a7; // IERC165
    }

    // ── ERC-2981 ─────────────────────────────────────────────────
    function royaltyInfo(uint256, uint256 salePrice) external view returns (address, uint256) {
        return (royaltyReceiver, (salePrice * royaltyBps) / 10000);
    }

    // ── ERC-1155 core ────────────────────────────────────────────
    function uri(uint256 tokenId) public view returns (string memory) {
        return string(abi.encodePacked(_uri, tokenId.toString(), ".json"));
    }
    function contractURI() external view returns (string memory) { return _contractURIValue; }
    function totalMinted() public view returns (uint256) { return _totalMinted; }

    function balanceOf(address account, uint256 id) public view returns (uint256) {
        require(account != address(0), "Zero addr"); return _balances[id][account];
    }
    function balanceOfBatch(address[] memory accounts, uint256[] memory ids) public view returns (uint256[] memory) {
        require(accounts.length == ids.length, "Length mismatch");
        uint256[] memory batchBalances = new uint256[](accounts.length);
        for (uint256 i = 0; i < accounts.length; i++) batchBalances[i] = _balances[ids[i]][accounts[i]];
        return batchBalances;
    }
    function setApprovalForAll(address operator, bool approved) public {
        require(operator != msg.sender, "Approve self");
        _operatorApprovals[msg.sender][operator] = approved;
        emit ApprovalForAll(msg.sender, operator, approved);
    }
    function isApprovedForAll(address account, address operator) public view returns (bool) {
        return _operatorApprovals[account][operator];
    }
    function safeTransferFrom(address from, address to, uint256 id, uint256 amount, bytes memory data) public {
        require(from == msg.sender || _operatorApprovals[from][msg.sender], "Not authorized");
        require(to != address(0), "Zero addr");
        require(_balances[id][from] >= amount, "Insufficient");
        _balances[id][from] -= amount;
        _balances[id][to] += amount;
        emit TransferSingle(msg.sender, from, to, id, amount);
        _checkSingleReceiver(msg.sender, from, to, id, amount, data);
    }
    function safeBatchTransferFrom(address from, address to, uint256[] memory ids, uint256[] memory amounts, bytes memory data) public {
        require(from == msg.sender || _operatorApprovals[from][msg.sender], "Not authorized");
        require(to != address(0), "Zero addr");
        require(ids.length == amounts.length, "Length mismatch");
        for (uint256 i = 0; i < ids.length; i++) {
            require(_balances[ids[i]][from] >= amounts[i], "Insufficient");
            _balances[ids[i]][from] -= amounts[i];
            _balances[ids[i]][to] += amounts[i];
        }
        emit TransferBatch(msg.sender, from, to, ids, amounts);
        _checkBatchReceiver(msg.sender, from, to, ids, amounts, data);
    }

    function _mint1155(address to, uint256 id, uint256 amount, bytes memory data) internal {
        require(to != address(0), "Zero addr");
        _balances[id][to] += amount;
        _totalMinted += amount;
        tokenSupply[id] += amount;
        emit TransferSingle(msg.sender, address(0), to, id, amount);
        _checkSingleReceiver(msg.sender, address(0), to, id, amount, data);
    }
    ${advanced.isBurnable ? `
    function _burn1155(address from, uint256 id, uint256 amount) internal {
        require(_balances[id][from] >= amount, "Insufficient");
        _balances[id][from] -= amount;
        _totalMinted -= amount;
        tokenSupply[id] -= amount;
        emit TransferSingle(msg.sender, from, address(0), id, amount);
    }` : ''}

    function _checkSingleReceiver(address op, address from, address to, uint256 id, uint256 amount, bytes memory data) internal {
        if (to.code.length > 0) {
            try IERC1155Receiver(to).onERC1155Received(op, from, id, amount, data) returns (bytes4 r) {
                require(r == IERC1155Receiver.onERC1155Received.selector, "Non-receiver");
            } catch { revert("Non-receiver"); }
        }
    }
    function _checkBatchReceiver(address op, address from, address to, uint256[] memory ids, uint256[] memory amounts, bytes memory data) internal {
        if (to.code.length > 0) {
            try IERC1155Receiver(to).onERC1155BatchReceived(op, from, ids, amounts, data) returns (bytes4 r) {
                require(r == IERC1155Receiver.onERC1155BatchReceived.selector, "Non-receiver");
            } catch { revert("Non-receiver"); }
        }
    }

    // ── Minting ──────────────────────────────────────────────────
    function mint(address to, uint256 id, uint256 amount, bytes memory data) external payable nonReentrant {
        require(!paused, "Minting paused");
        require(amount > 0, "Zero amount");
        require(_totalMinted + amount <= maxSupply, "Max supply exceeded");
        require(msg.value >= cost * amount, "Insufficient payment");
        mintedByWallet[to] += amount;
        _mint1155(to, id, amount, data);
        emit Minted(to, id, amount);
    }

    function ownerMint(address to, uint256 id, uint256 amount) external onlyOwner {
        require(_totalMinted + amount <= maxSupply, "Max supply exceeded");
        _mint1155(to, id, amount, "");
        emit Minted(to, id, amount);
    }

    function ownerMintBatch(address to, uint256[] calldata ids, uint256[] calldata amounts) external onlyOwner {
        uint256 total;
        for (uint256 i = 0; i < amounts.length; i++) total += amounts[i];
        require(_totalMinted + total <= maxSupply, "Max supply exceeded");
        for (uint256 i = 0; i < ids.length; i++) {
            _balances[ids[i]][to] += amounts[i];
            _totalMinted += amounts[i];
            tokenSupply[ids[i]] += amounts[i];
        }
        emit TransferBatch(msg.sender, address(0), to, ids, amounts);
    }

    ${advanced.isBurnable ? `
    function burn(address from, uint256 id, uint256 amount) external {
        require(from == msg.sender || _operatorApprovals[from][msg.sender], "Not authorized");
        _burn1155(from, id, amount);
    }` : ''}

    // ── Admin ────────────────────────────────────────────────────
    function setURI(string calldata newUri) external onlyOwner { _uri = newUri; emit URI(newUri, 0); }
    function setCost(uint256 _cost) external onlyOwner { cost = _cost; }
    function setPaused(bool _state) external onlyOwner { paused = _state; }
    function setRoyalty(address recv, uint96 bps) external onlyOwner {
        require(bps <= 1000, "Max 10%"); royaltyReceiver = recv; royaltyBps = bps;
    }
    function setContractURI(string calldata uri_) external onlyOwner { _contractURIValue = uri_; }

    function withdraw() external onlyOwner nonReentrant {
        uint256 bal = address(this).balance;
        require(bal > 0, "Nothing to withdraw");
        (bool ok,) = payable(_owner).call{value: bal}("");
        require(ok, "Transfer failed");
    }
}
`;
}
