

export interface TokenConfig {
  
  name: string;
  symbol: string;
  decimals: number;
  initialSupply: string;
  
  isMintable: boolean;
  isBurnable: boolean;
  isPausable: boolean;
  
  hasTax: boolean;
  taxBps: number;
  taxRecipient: string;
  maxSupply?: string;
  
  isGovernance: boolean;      
  hasPermit: boolean;         
  hasFlashMint: boolean;      
  hasBlacklist: boolean;      
  useRoles: boolean;          
  logoURI: string;            
}



export function generateTokenSource(config: TokenConfig): string {
  const {
    name, symbol, decimals, initialSupply,
    isMintable, isBurnable, isPausable,
    hasTax, taxBps, taxRecipient, maxSupply,
    isGovernance, hasPermit, hasFlashMint, hasBlacklist, useRoles, logoURI,
  } = config;

  const cn            = (name || 'Token').replace(/[^a-zA-Z0-9_]/g, '').replace(/^[0-9]+/, '') || 'Token';
  const safeRecipient = taxRecipient && /^0x[0-9a-fA-F]{40}$/.test(taxRecipient) ? taxRecipient : '';
  const safeLogo      = (logoURI || '').replace(/"/g, '\\"');

  // Permit needs EIP-712 domain separator — we inline a minimal implementation
  const needsPermit   = hasPermit || isGovernance; // Votes builds on Permit

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// =================================================================
// ${name} (${symbol})
// Generated by Crolana — self-contained, zero dependencies
// Features: ${[
    isMintable  ? 'Mintable'   : '',
    isBurnable  ? 'Burnable'   : '',
    isPausable  ? 'Pausable'   : '',
    hasTax      ? 'Tax'        : '',
    maxSupply   ? 'Capped'     : '',
    hasPermit   ? 'EIP-2612'   : '',
    isGovernance? 'Votes'      : '',
    hasFlashMint? 'FlashMint'  : '',
    hasBlacklist? 'Blacklist'  : '',
    useRoles    ? 'Roles'      : '',
    logoURI     ? 'LogoURI'    : '',
  ].filter(Boolean).join(', ') || 'Basic'}
// =================================================================

contract ${cn} {

    // ── Events ───────────────────────────────────────────────────
    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    ${isPausable    ? 'event Paused(address account);\n    event Unpaused(address account);' : ''}
    ${isGovernance  ? 'event DelegateChanged(address indexed delegator, address indexed fromDelegate, address indexed toDelegate);\n    event DelegateVotesChanged(address indexed delegate, uint256 previousVotes, uint256 newVotes);' : ''}
    ${hasFlashMint  ? 'event FlashLoan(address indexed receiver, address indexed token, uint256 value, uint256 fee);' : ''}
    ${useRoles      ? 'event RoleGranted(bytes32 indexed role, address indexed account);\n    event RoleRevoked(bytes32 indexed role, address indexed account);' : ''}
    ${logoURI       ? 'event LogoURIUpdated(string newURI);' : ''}

    // ── Storage ──────────────────────────────────────────────────
    string public name     = "${name}";
    string public symbol   = "${symbol}";
    uint8  public decimals = ${decimals};
    uint256 private _totalSupply;

    ${!useRoles ? `address private _owner;` : ''}
    ${isPausable    ? 'bool private _paused;' : ''}
    ${maxSupply     ? `uint256 public constant MAX_SUPPLY = ${maxSupply}e${decimals};` : ''}
    ${hasTax        ? `uint256 public taxBps = ${taxBps};\n    address public taxRecipient;\n    mapping(address => bool) public isExcludedFromTax;` : ''}
    ${hasBlacklist  ? 'mapping(address => bool) public isBlacklisted;' : ''}
    ${logoURI       ? `string private _logoURI = "${safeLogo}";` : ''}

    mapping(address => uint256)                            private _balances;
    mapping(address => mapping(address => uint256))        private _allowances;

    ${needsPermit ? `
    // ── EIP-712 / EIP-2612 Permit ────────────────────────────────
    bytes32 private immutable _DOMAIN_SEPARATOR;
    mapping(address => uint256) public nonces;
    bytes32 private constant PERMIT_TYPEHASH =
        keccak256("Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)");
    ` : ''}

    ${isGovernance ? `
    // ── ERC-20Votes (delegation + checkpoints) ───────────────────
    struct Checkpoint { uint32 fromBlock; uint224 votes; }
    mapping(address => address)                     private _delegates;
    mapping(address => Checkpoint[])                private _checkpoints;
    Checkpoint[]                                    private _totalSupplyCheckpoints;
    bytes32 private constant DELEGATION_TYPEHASH =
        keccak256("Delegation(address delegatee,uint256 nonce,uint256 expiry)");
    ` : ''}

    ${useRoles ? `
    // ── AccessControl roles ───────────────────────────────────────
    bytes32 public constant MINTER_ROLE  = keccak256("MINTER_ROLE");
    bytes32 public constant PAUSER_ROLE  = keccak256("PAUSER_ROLE");
    bytes32 public constant ADMIN_ROLE   = 0x00; // DEFAULT_ADMIN_ROLE
    mapping(bytes32 => mapping(address => bool)) private _roles;
    ` : ''}

    // ── Constructor ──────────────────────────────────────────────
    constructor() {
        ${!useRoles ? `_owner = msg.sender;\n        emit OwnershipTransferred(address(0), msg.sender);` : ''}
        ${useRoles  ? `_roles[ADMIN_ROLE][msg.sender]  = true;\n        _roles[MINTER_ROLE][msg.sender] = true;\n        _roles[PAUSER_ROLE][msg.sender] = true;\n        emit RoleGranted(ADMIN_ROLE,  msg.sender);\n        emit RoleGranted(MINTER_ROLE, msg.sender);\n        emit RoleGranted(PAUSER_ROLE, msg.sender);` : ''}
        ${hasTax    ? `taxRecipient = ${safeRecipient !== '' ? safeRecipient : 'msg.sender'};\n        isExcludedFromTax[msg.sender] = true;` : ''}
        _mint(msg.sender, ${initialSupply} * (10 ** ${decimals}));
        ${needsPermit ? `
        _DOMAIN_SEPARATOR = keccak256(abi.encode(
            keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),
            keccak256(bytes(name)),
            keccak256(bytes("1")),
            block.chainid,
            address(this)
        ));` : ''}
    }

    // ── Ownership / Access ───────────────────────────────────────
    ${!useRoles ? `
    modifier onlyOwner() { require(msg.sender == _owner, "Not owner"); _; }
    function owner() public view returns (address) { return _owner; }
    function renounceOwnership() external onlyOwner {
        emit OwnershipTransferred(_owner, address(0));
        _owner = address(0);
    }
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Zero address");
        emit OwnershipTransferred(_owner, newOwner);
        _owner = newOwner;
    }` : ''}

    ${useRoles ? `
    modifier onlyRole(bytes32 role) { require(_roles[role][msg.sender], "Missing role"); _; }
    function hasRole(bytes32 role, address account) public view returns (bool) { return _roles[role][account]; }
    function grantRole(bytes32 role, address account) external onlyRole(ADMIN_ROLE) {
        _roles[role][account] = true;
        emit RoleGranted(role, account);
    }
    function revokeRole(bytes32 role, address account) external onlyRole(ADMIN_ROLE) {
        _roles[role][account] = false;
        emit RoleRevoked(role, account);
    }
    // Convenience alias so existing callers work
    modifier onlyOwner() { require(_roles[ADMIN_ROLE][msg.sender], "Not admin"); _; }
    ` : ''}

    ${isPausable ? `
    // ── Pausable ─────────────────────────────────────────────────
    modifier whenNotPaused() { require(!_paused, "Paused"); _; }
    function paused() public view returns (bool) { return _paused; }
    function pause()   external ${useRoles ? 'onlyRole(PAUSER_ROLE)' : 'onlyOwner'} { _paused = true;  emit Paused(msg.sender); }
    function unpause() external ${useRoles ? 'onlyRole(PAUSER_ROLE)' : 'onlyOwner'} { _paused = false; emit Unpaused(msg.sender); }
    ` : ''}

    ${hasBlacklist ? `
    // ── Blacklist ────────────────────────────────────────────────
    function setBlacklisted(address account, bool flag) external onlyOwner {
        isBlacklisted[account] = flag;
    }
    modifier notBlacklisted(address a) { require(!isBlacklisted[a], "Blacklisted"); _; }
    ` : ''}

    // ── ERC-20 Core ──────────────────────────────────────────────
    function totalSupply() public view returns (uint256) { return _totalSupply; }
    function balanceOf(address account) public view returns (uint256) { return _balances[account]; }

    function transfer(address to, uint256 amount) public ${isPausable ? 'whenNotPaused ' : ''}${hasBlacklist ? 'notBlacklisted(msg.sender) notBlacklisted(to) ' : ''}returns (bool) {
        _transfer(msg.sender, to, amount);
        return true;
    }
    function allowance(address tokenOwner, address spender) public view returns (uint256) {
        return _allowances[tokenOwner][spender];
    }
    function approve(address spender, uint256 amount) public ${hasBlacklist ? 'notBlacklisted(msg.sender) ' : ''}returns (bool) {
        _allowances[msg.sender][spender] = amount;
        emit Approval(msg.sender, spender, amount);
        return true;
    }
    function transferFrom(address from, address to, uint256 amount) public ${isPausable ? 'whenNotPaused ' : ''}${hasBlacklist ? 'notBlacklisted(from) notBlacklisted(to) ' : ''}returns (bool) {
        uint256 allowed = _allowances[from][msg.sender];
        require(allowed >= amount, "Insufficient allowance");
        if (allowed != type(uint256).max) _allowances[from][msg.sender] = allowed - amount;
        _transfer(from, to, amount);
        return true;
    }
    function increaseAllowance(address spender, uint256 addedValue) public returns (bool) {
        _allowances[msg.sender][spender] += addedValue;
        emit Approval(msg.sender, spender, _allowances[msg.sender][spender]);
        return true;
    }
    function decreaseAllowance(address spender, uint256 subtractedValue) public returns (bool) {
        uint256 current = _allowances[msg.sender][spender];
        require(current >= subtractedValue, "Below zero");
        _allowances[msg.sender][spender] = current - subtractedValue;
        emit Approval(msg.sender, spender, _allowances[msg.sender][spender]);
        return true;
    }

    function _transfer(address from, address to, uint256 amount) internal {
        require(from != address(0) && to != address(0), "Zero address");
        require(_balances[from] >= amount, "Insufficient balance");
        ${hasTax ? `
        if (taxBps > 0 && taxRecipient != address(0) && !isExcludedFromTax[from] && !isExcludedFromTax[to]) {
            uint256 tax = (amount * taxBps) / 10000;
            _balances[from]         -= amount;
            _balances[taxRecipient] += tax;
            _balances[to]           += (amount - tax);
            emit Transfer(from, taxRecipient, tax);
            emit Transfer(from, to, amount - tax);
        } else {
            _balances[from] -= amount;
            _balances[to]   += amount;
            emit Transfer(from, to, amount);
        }` : `
        _balances[from] -= amount;
        _balances[to]   += amount;
        emit Transfer(from, to, amount);`}
        ${isGovernance ? `_moveVotingPower(_delegates[from], _delegates[to], amount);` : ''}
    }

    function _mint(address account, uint256 amount) internal {
        require(account != address(0), "Zero address");
        ${maxSupply ? `require(_totalSupply + amount <= MAX_SUPPLY, "Exceeds cap");` : ''}
        _totalSupply       += amount;
        _balances[account] += amount;
        emit Transfer(address(0), account, amount);
        ${isGovernance ? `_writeCheckpoint(_totalSupplyCheckpoints, _add, amount);` : ''}
    }

    function _burn(address account, uint256 amount) internal {
        require(_balances[account] >= amount, "Burn exceeds balance");
        _balances[account] -= amount;
        _totalSupply       -= amount;
        emit Transfer(account, address(0), amount);
        ${isGovernance ? `_writeCheckpoint(_totalSupplyCheckpoints, _subtract, amount);` : ''}
    }

    ${isMintable ? `
    // ── Mint ──────────────────────────────────────────────────────
    function mint(address to, uint256 amount) external ${useRoles ? 'onlyRole(MINTER_ROLE)' : 'onlyOwner'} {
        _mint(to, amount);
    }` : ''}

    ${isBurnable ? `
    // ── Burn ──────────────────────────────────────────────────────
    function burn(uint256 amount) external { _burn(msg.sender, amount); }
    function burnFrom(address account, uint256 amount) external {
        uint256 allowed = _allowances[account][msg.sender];
        require(allowed >= amount, "Allowance exceeded");
        if (allowed != type(uint256).max) _allowances[account][msg.sender] = allowed - amount;
        _burn(account, amount);
    }` : ''}

    ${hasTax ? `
    // ── Tax ───────────────────────────────────────────────────────
    function setTaxBps(uint256 _bps) external onlyOwner { require(_bps <= 1000, "Max 10%"); taxBps = _bps; }
    function setTaxRecipient(address _r) external onlyOwner { require(_r != address(0), "Zero addr"); taxRecipient = _r; }
    function setExcludedFromTax(address account, bool excluded) external onlyOwner { isExcludedFromTax[account] = excluded; }
    ` : ''}

    ${needsPermit ? `
    // ── EIP-2612 Permit ───────────────────────────────────────────
    function DOMAIN_SEPARATOR() external view returns (bytes32) { return _DOMAIN_SEPARATOR; }
    function permit(
        address owner_, address spender, uint256 value,
        uint256 deadline, uint8 v, bytes32 r, bytes32 s
    ) external {
        require(block.timestamp <= deadline, "Permit expired");
        bytes32 structHash = keccak256(abi.encode(PERMIT_TYPEHASH, owner_, spender, value, nonces[owner_]++, deadline));
        bytes32 hash = keccak256(abi.encodePacked("\\x19\\x01", _DOMAIN_SEPARATOR, structHash));
        address signer = ecrecover(hash, v, r, s);
        require(signer != address(0) && signer == owner_, "Invalid signature");
        _allowances[owner_][spender] = value;
        emit Approval(owner_, spender, value);
    }` : ''}

    ${isGovernance ? `
    // ── ERC-20Votes ───────────────────────────────────────────────
    function getVotes(address account) public view returns (uint256) {
        uint256 pos = _checkpoints[account].length;
        return pos == 0 ? 0 : _checkpoints[account][pos - 1].votes;
    }
    function getPastVotes(address account, uint256 blockNumber) public view returns (uint256) {
        require(blockNumber < block.number, "Not yet mined");
        return _checkpointsLookup(_checkpoints[account], blockNumber);
    }
    function getPastTotalSupply(uint256 blockNumber) public view returns (uint256) {
        require(blockNumber < block.number, "Not yet mined");
        return _checkpointsLookup(_totalSupplyCheckpoints, blockNumber);
    }
    function delegates(address account) public view returns (address) { return _delegates[account]; }
    function delegate(address delegatee) external {
        _delegate(msg.sender, delegatee);
    }
    function delegateBySig(address delegatee, uint256 nonce, uint256 expiry, uint8 v, bytes32 r, bytes32 s) external {
        require(block.timestamp <= expiry, "Sig expired");
        bytes32 structHash = keccak256(abi.encode(DELEGATION_TYPEHASH, delegatee, nonce, expiry));
        bytes32 hash = keccak256(abi.encodePacked("\\x19\\x01", _DOMAIN_SEPARATOR, structHash));
        address signer = ecrecover(hash, v, r, s);
        require(signer != address(0), "Invalid sig");
        require(nonces[signer]++ == nonce, "Invalid nonce");
        _delegate(signer, delegatee);
    }
    function _delegate(address delegator, address delegatee) internal {
        address currentDelegate = _delegates[delegator];
        _delegates[delegator] = delegatee;
        emit DelegateChanged(delegator, currentDelegate, delegatee);
        _moveVotingPower(currentDelegate, delegatee, balanceOf(delegator));
    }
    function _moveVotingPower(address src, address dst, uint256 amount) internal {
        if (src != dst && amount > 0) {
            if (src != address(0)) {
                (uint256 oldW, uint256 newW) = _writeCheckpoint(_checkpoints[src], _subtract, amount);
                emit DelegateVotesChanged(src, oldW, newW);
            }
            if (dst != address(0)) {
                (uint256 oldW, uint256 newW) = _writeCheckpoint(_checkpoints[dst], _add, amount);
                emit DelegateVotesChanged(dst, oldW, newW);
            }
        }
    }
    function _writeCheckpoint(Checkpoint[] storage ckpts, function(uint256,uint256) pure returns (uint256) op, uint256 delta)
        internal returns (uint256 oldWeight, uint256 newWeight)
    {
        uint256 pos = ckpts.length;
        oldWeight = pos == 0 ? 0 : ckpts[pos - 1].votes;
        newWeight = op(oldWeight, delta);
        if (pos > 0 && ckpts[pos - 1].fromBlock == block.number) {
            ckpts[pos - 1].votes = uint224(newWeight);
        } else {
            ckpts.push(Checkpoint({ fromBlock: uint32(block.number), votes: uint224(newWeight) }));
        }
    }
    function _checkpointsLookup(Checkpoint[] storage ckpts, uint256 blockNumber) private view returns (uint256) {
        uint256 len = ckpts.length;
        if (len == 0) return 0;
        if (ckpts[len - 1].fromBlock <= blockNumber) return ckpts[len - 1].votes;
        if (ckpts[0].fromBlock > blockNumber) return 0;
        uint256 lo = 0; uint256 hi = len - 1;
        while (lo < hi) {
            uint256 mid = (lo + hi + 1) / 2;
            if (ckpts[mid].fromBlock <= blockNumber) lo = mid; else hi = mid - 1;
        }
        return ckpts[lo].votes;
    }
    function _add(uint256 a, uint256 b) private pure returns (uint256) { return a + b; }
    function _subtract(uint256 a, uint256 b) private pure returns (uint256) { return a - b; }
    ` : ''}

    ${hasFlashMint ? `
    // ── ERC-3156 Flash Mint ───────────────────────────────────────
    bytes32 private constant FLASH_LOAN_CALLBACK = keccak256("ERC3156FlashBorrower.onFlashLoan");
    function maxFlashLoan(address token) external view returns (uint256) {
        return token == address(this) ? type(uint256).max - _totalSupply : 0;
    }
    function flashFee(address token, uint256) external view returns (uint256) {
        require(token == address(this), "Unsupported token");
        return 0; // zero fee — override to charge
    }
    function flashLoan(address receiver, address token, uint256 amount, bytes calldata data) external returns (bool) {
        require(token == address(this), "Unsupported token");
        _mint(receiver, amount);
        require(
            IERC3156FlashBorrower(receiver).onFlashLoan(msg.sender, token, amount, 0, data) == FLASH_LOAN_CALLBACK,
            "Invalid callback"
        );
        uint256 allowance_ = _allowances[receiver][address(this)];
        require(allowance_ >= amount, "Repayment not approved");
        _allowances[receiver][address(this)] = allowance_ - amount;
        _burn(receiver, amount);
        emit FlashLoan(receiver, token, amount, 0);
        return true;
    }
    ` : ''}

    ${logoURI ? `
    // ── Logo / Metadata URI ───────────────────────────────────────
    // Non-standard extension — wallets, token lists, explorers use this
    // to display the token logo without an off-chain registry.
    function logoURI() public view returns (string memory) { return _logoURI; }
    function setLogoURI(string calldata newURI) external onlyOwner {
        _logoURI = newURI;
        emit LogoURIUpdated(newURI);
    }
    ` : ''}

    // ── Recover accidentally sent tokens ─────────────────────────
    function rescueTokens(address token, address to, uint256 amount) external onlyOwner {
        require(token != address(this), "Cannot rescue self");
        (bool ok,) = token.call(abi.encodeWithSignature("transfer(address,uint256)", to, amount));
        require(ok, "Transfer failed");
    }
}

${hasFlashMint ? `
interface IERC3156FlashBorrower {
    function onFlashLoan(address initiator, address token, uint256 amount, uint256 fee, bytes calldata data)
        external returns (bytes32);
}` : ''}
`;
}

// ─── Validation ───────────────────────────────────────────────────────────────

export function validateTokenConfig(config: Partial<TokenConfig>): string[] {
  const errors: string[] = [];
  if (!config.name?.trim())    errors.push('Token name is required');
  if (!config.symbol?.trim())  errors.push('Token symbol is required');
  if (config.symbol && (config.symbol.length < 2 || config.symbol.length > 8)) errors.push('Symbol must be 2-8 characters');
  if (!config.initialSupply || isNaN(Number(config.initialSupply)) || Number(config.initialSupply) <= 0)
    errors.push('Initial supply must be a positive number');
  if (config.hasTax && (config.taxBps ?? 0) > 1000) errors.push('Tax must be <= 10% (1000 bps)');
  if (config.decimals !== undefined && (config.decimals < 0 || config.decimals > 18)) errors.push('Decimals must be 0-18');
  return errors;
}

// ─── Defaults & templates ─────────────────────────────────────────────────────

export const DEFAULT_TOKEN_CONFIG: TokenConfig = {
  name: '', symbol: '', decimals: 18, initialSupply: '1000000',
  isMintable: false, isBurnable: false, isPausable: false,
  hasTax: false, taxBps: 0, taxRecipient: '',
  isGovernance: false, hasPermit: false, hasFlashMint: false,
  hasBlacklist: false, useRoles: false, logoURI: '',
};

export interface TokenTemplate {
  id: string; name: string; description: string; config: Partial<TokenConfig>;
}

export const TOKEN_TEMPLATES: TokenTemplate[] = [
  { id: 'basic',      name: 'Basic Token',      description: 'Fixed supply — clean and simple',                     config: {} },
  { id: 'utility',    name: 'Utility Token',     description: 'Mintable + burnable + pausable',                     config: { isMintable: true, isBurnable: true, isPausable: true } },
  { id: 'defla',      name: 'Deflationary',      description: 'Holders can burn to reduce supply',                  config: { isBurnable: true } },
  { id: 'tax',        name: 'Tax Token',          description: 'Auto transfer tax → treasury',                       config: { hasTax: true, taxBps: 300, isBurnable: true } },
  { id: 'governance', name: 'Governance Token',   description: 'Votes + delegation + EIP-2612 permit',               config: { isGovernance: true, hasPermit: true, useRoles: true, isBurnable: true } },
  { id: 'modern',     name: 'Modern Full-Featured', description: 'All extensions: votes, permit, roles, logo, blacklist', config: { isGovernance: true, hasPermit: true, useRoles: true, isMintable: true, isBurnable: true, isPausable: true, hasBlacklist: false } },
];
